export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const FETCH_USERS = 'FETCH_USERS';
export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const REMOVE_PRODUCT_FROM_BASKET = "REMOVE_PRODUCT_FROM_BASKET";

export const CLEAN_BASKET = "CLEAN_BASKET";

export const INCREASE_DAYS_TO_RENT = "INCREASE_DAYS_TO_RENT";
export const DECREASE_DAYS_TO_RENT = "DECREASE_DAYS_TO_RENT";

export const ON_QUANTITY_CHANGE = "ON_QUANTITY_CHANGE";